/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 헬스체크 + Cloud Run 워밍업
         * @description 발표 직전 이 엔드포인트를 한 번 때려 인스턴스를 깨워둔다.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 메뉴판 사진 1장 → 메뉴 목록
         * @description 목록에 필요한 것만 반환한다. 긴 설명·알레르기 근거는 `/menu/item/explain` 으로.
         */
        post: operations["scan_menu_api_v1_menu_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/item/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 메뉴 1개의 상세 설명 (카드를 탭했을 때)
         * @description 사진을 다시 보내지 않는다 — 텍스트 전용이라 목록 호출보다 훨씬 싸고 빠르다.
         *
         *     클라이언트는 결과를 scan_id 와 함께 캐시해서 같은 메뉴를 두 번 묻지 않는다.
         */
        post: operations["explain_item_api_v1_menu_item_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/locate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 장바구니 항목을 메뉴판 사진 위에서 찾기 (사진에서 확인 탭)
         * @description 사용자가 '사진에서 확인' 탭을 열 때만 호출한다. 대상은 장바구니의 몇 개뿐이라
         *     목록 스캔처럼 항목 수로 곱해지지 않는다. 좌표는 Gemini 네이티브 0~1000 을 받아 0~1 로 변환해 내려준다.
         */
        post: operations["locate_items_api_v1_menu_locate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 점원 대화 — 자유 발화 번역
         * @description 주문 '카드'는 서버를 부르지 않는다(오프라인 조립). 이건 자유 발화 번역 전용이다.
         */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 점원 대화 — 음성 받아쓰기 + 번역
         * @description 홀드-투-토크 녹음을 받아 Gemini 오디오로 전사+번역한다.
         */
        post: operations["chat_voice_api_v1_chat_voice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_chat_voice_api_v1_chat_voice_post */
        Body_chat_voice_api_v1_chat_voice_post: {
            /**
             * Audio
             * Format: binary
             * @description 짧은 발화 오디오 (webm/mp4/m4a 등)
             */
            audio: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "ko2local" | "local2ko";
            /**
             * Source Lang
             * @default ja
             */
            source_lang: string;
        };
        /** Body_locate_items_api_v1_menu_locate_post */
        Body_locate_items_api_v1_menu_locate_post: {
            /**
             * Image
             * Format: binary
             * @description 메뉴판 사진 (스캔 때와 같은 축소본)
             */
            image: string;
            /**
             * Targets
             * @description 찾을 항목 JSON. 예: [{"index":1,"name_local":"ラフテー","section":"돼지고기 요리"}]
             */
            targets: string;
        };
        /** Body_scan_menu_api_v1_menu_scan_post */
        Body_scan_menu_api_v1_menu_scan_post: {
            /**
             * Image
             * Format: binary
             * @description 메뉴판 사진 (JPEG/PNG/WEBP)
             */
            image: string;
            /**
             * Mode
             * @description 촬영 모드
             * @default poster
             * @enum {string}
             */
            mode: "poster" | "booklet" | "kiosk";
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Text
             * @description 번역할 한 문장
             */
            text: string;
            /**
             * Source Lang
             * @description 현지어 BCP-47. 스캔 응답의 source_lang
             * @default ja
             */
            source_lang: string;
            /**
             * Direction
             * @description ko2local: 내 한국어→현지어 / local2ko: 점원 현지어→한국어
             * @enum {string}
             */
            direction: "ko2local" | "local2ko";
        };
        /** ChatResponse */
        ChatResponse: {
            /**
             * Translated
             * @description 번역문. 방향에 따라 현지어 또는 한국어.
             */
            translated: string;
            /**
             * Reading
             * @description ko2local 이면 번역한 현지어의 한국어 독음(소리내어 말할 때). 예: 'パクチー抜きで' → '파쿠치- 누키데'. local2ko 이면 빈 문자열.
             */
            reading: string;
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /** ExplainRequest */
        ExplainRequest: {
            /**
             * Name Local
             * @description 1단계 응답의 name_local 을 그대로
             */
            name_local: string;
            /**
             * Name Translated
             * @default
             */
            name_translated: string;
            /**
             * Source Lang
             * @description 1단계 응답의 source_lang
             * @default ja
             */
            source_lang: string;
            /**
             * Cuisine Hint
             * @description 가게 성격. 있으면 설명이 정확해진다
             * @default
             */
            cuisine_hint: string;
        };
        /** ExplainResponse */
        ExplainResponse: {
            /**
             * Romanization
             * @description 현지어 발음의 로마자 표기. 모르면 빈 문자열.
             */
            romanization: string;
            /**
             * Pronunciation Ko
             * @description 한국어 독음. 점원에게 소리내어 말할 때 쓴다. 예: '라후테-'
             */
            pronunciation_ko: string;
            /**
             * Description
             * @description 어떤 음식인지 2~3문장. 맛·식감·조리법·먹는 방법 중심. 호불호가 갈릴 요소(쓴맛, 강한 향신료, 높은 도수, 생식)는 반드시 언급.
             */
            description: string;
            /**
             * Tip
             * @description 한국인 여행자에게 도움이 될 조언 한두 문장. 주문 요령, 양, 곁들임 등. 해당 사항이 없으면 빈 문자열.
             */
            tip: string;
            /**
             * Allergens
             * @description 메뉴명·재료로 정당화할 수 있는 것만. 근거를 댈 수 없으면 넣지 말 것.
             */
            allergens: components["schemas"]["LikelyAllergen"][];
            /** Name Local */
            name_local: string;
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Model */
            model: string;
            /** Has Api Key */
            has_api_key: boolean;
        };
        /**
         * ItemBox
         * @description 한 항목의 정규화 위치(0~1). 서버가 Gemini 의 0~1000 을 변환해 내려준다.
         */
        ItemBox: {
            /** Index */
            index: number;
            /** Name Local */
            name_local: string;
            /** Found */
            found: boolean;
            /**
             * X
             * @description 왼쪽. 이미지 너비 대비 0~1 (좌상단 원점, 세운 이미지 기준)
             */
            x: number;
            /**
             * Y
             * @description 위쪽. 이미지 높이 대비 0~1
             */
            y: number;
            /**
             * W
             * @description 너비 0~1
             */
            w: number;
            /**
             * H
             * @description 높이 0~1
             */
            h: number;
        };
        /**
         * LikelyAllergen
         * @description ⚠️ 메뉴판에서 '읽은' 사실이 아니라 요리 지식에서 '추론한' 값이다.
         *
         *     UI 는 반드시 추정임을 고지해야 한다. 식품 안전 문제라 이 구분이 중요하다.
         */
        LikelyAllergen: {
            /**
             * Code
             * @description 표준 알레르기 코드
             * @enum {string}
             */
            code: "egg" | "milk" | "buckwheat" | "peanut" | "soy" | "wheat" | "gluten" | "mackerel" | "fish" | "crab" | "shrimp" | "crustacean" | "squid" | "shellfish" | "mollusk" | "pork" | "beef" | "chicken" | "peach" | "tomato" | "sulfite" | "walnut" | "pine_nut" | "tree_nut" | "sesame" | "celery" | "mustard" | "alcohol" | "other";
            /**
             * Label
             * @description 한국어 표시명. 예: '새우'
             */
            label: string;
            /**
             * Inferred
             * @description 메뉴판에 명시돼 있지 않고 요리 지식으로 추론했으면 true. 대부분 true 다.
             */
            inferred: boolean;
            /**
             * Basis
             * @description 그렇게 판단한 근거를 한국어 한 문장으로. 예: "메뉴명에 'エビ'(새우)가 있음"
             */
            basis: string;
            /**
             * Confidence
             * @description 확신도
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
        };
        /** LocateResponse */
        LocateResponse: {
            /** Boxes */
            boxes: components["schemas"]["ItemBox"][];
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /**
         * MenuItemSummary
         * @description 결과 목록 카드에 바로 필요한 것만. 여기에 필드를 늘리면 항목 수만큼 곱해진다.
         */
        MenuItemSummary: {
            /**
             * Name Local
             * @description 메뉴판에 적힌 원문 그대로. 절대 번역·정규화하지 말 것. 장음부호(ー)나 가나 표기도 보이는 대로. 사용자가 이 글자를 점원에게 그대로 보여준다.
             */
            name_local: string;
            /**
             * Name Translated
             * @description 한국어 번역명. 음차가 자연스러우면 음차.
             */
            name_translated: string;
            /**
             * Price Text
             * @description 가격을 적힌 그대로. 예: '970円', '¥970', '時価'. 못 읽었으면 빈 문자열.
             */
            price_text: string;
            /**
             * Price Amount
             * @description price_text 에서 파싱한 숫자만. 범위·시가·판독 불가면 null. 소수점이 **적혀 있을 때만** 소수로: '$3.50'→3.5, '970円'→970(970.0 이 아니라 970).
             */
            price_amount: number | null;
            /**
             * Tax Included
             * @description 税込이면 true, 税抜/+税면 false, 표기가 없으면 null.
             */
            tax_included: boolean | null;
            /**
             * Category
             * @description 분류
             * @enum {string}
             */
            category: "food" | "drink" | "dessert" | "set" | "unknown";
            /**
             * Section
             * @description 이 항목이 메뉴판에서 어느 분류 아래 적혀 있는지, 그 분류 제목을 한국어로. 예: '튀김', '찬푸르', '국물', '130엔 접시'. **메뉴판에 실제로 적힌 분류만 쓸 것** — 분류 제목이 없는 메뉴판이면 빈 문자열. 직접 분류를 만들어내지 말 것.
             */
            section: string;
            /**
             * Summary
             * @description 이게 무슨 음식인지 한 줄로. **25자 이내.** 예: '흑설탕에 조린 삼겹살'. 긴 설명은 여기 쓰지 말 것 — 사용자가 카드를 탭하면 따로 받아온다.
             */
            summary: string;
            /**
             * Image Query
             * @description 이 요리의 참고 사진을 위키미디어 커먼즈에서 찾기 위한 영문/로마자 검색어 한 개. 가장 널리 통용되는 요리명으로. 예: 'tamagoyaki', 'goya champuru', 'okinawa soba', 'gurukun fried fish'. 재료+조리법 조합이면 그렇게(예: 'fried island scallion'). 커먼즈 파일 제목이 대부분 영문이라 원문보다 영문이 잘 맞는다. 모르면 빈 문자열.
             */
            image_query: string;
            /**
             * Tags
             * @description 해당하는 것만. 없으면 빈 배열.
             */
            tags: ("signature" | "local" | "caution" | "spicy" | "raw" | "vegetarian" | "vegan" | "pork" | "beef" | "chicken" | "seafood" | "alcohol" | "share" | "single_portion" | "noodle" | "rice" | "soup" | "fried" | "dessert")[];
            /**
             * Allergens
             * @description 메뉴명·재료로 정당화할 수 있는 알레르기 코드만. 근거를 댈 수 없으면 넣지 말 것. 억지로 채우지 말 것. (근거 문장은 상세 조회에서 따로 받는다)
             */
            allergens: ("egg" | "milk" | "buckwheat" | "peanut" | "soy" | "wheat" | "gluten" | "mackerel" | "fish" | "crab" | "shrimp" | "crustacean" | "squid" | "shellfish" | "mollusk" | "pork" | "beef" | "chicken" | "peach" | "tomato" | "sulfite" | "walnut" | "pine_nut" | "tree_nut" | "sesame" | "celery" | "mustard" | "alcohol" | "other")[];
            /**
             * Ocr Confidence
             * @description 이 항목의 글자를 얼마나 확실히 읽었는지
             * @enum {string}
             */
            ocr_confidence: "high" | "medium" | "low";
        };
        /** MenuScanResponse */
        MenuScanResponse: {
            /**
             * Source Lang
             * @description 메뉴판 언어의 BCP-47 코드. 예: 'ja', 'th', 'vi'
             */
            source_lang: string;
            /**
             * Currency
             * @description ISO 4217 통화 코드. 예: 'JPY'. 모르면 빈 문자열.
             */
            currency: string;
            restaurant: components["schemas"]["Restaurant"];
            /**
             * Items
             * @description 메뉴판에서 읽은 항목 전부. 사진에 없는 메뉴를 지어내지 말 것. 카테고리 제목(예: '一品料理')이나 가격대 제목(예: '皿 一三〇円')은 항목이 아니므로 제외. 단, 가격대 제목 아래 나열된 항목들에는 그 가격을 각각 채워 넣을 것.
             */
            items: components["schemas"]["MenuItemSummary"][];
            /**
             * Warnings
             * @description 사용자에게 알려야 할 문제를 한국어로. 예: '메뉴판 오른쪽이 잘려 일부를 읽지 못했어요'. 문제가 없으면 빈 배열.
             */
            warnings: string[];
            /** Scan Id */
            scan_id: string;
            meta: components["schemas"]["ScanMeta"];
        };
        /** Restaurant */
        Restaurant: {
            /**
             * Name Local
             * @description 사진에서 읽은 가게 이름 원문. 없으면 빈 문자열.
             */
            name_local: string;
            /**
             * Name Translated
             * @description 한국어 표기. 없으면 빈 문자열.
             */
            name_translated: string;
            /**
             * Cuisine Hint
             * @description 음식 종류 한 마디. 예: '오키나와 가정식'. 모르면 빈 문자열.
             */
            cuisine_hint: string;
        };
        /** ScanMeta */
        ScanMeta: {
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
            /** Image Px */
            image_px: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VoiceResponse */
        VoiceResponse: {
            /**
             * Source Text
             * @description 말한 내용을 원래 언어 그대로 받아쓴 것
             */
            source_text: string;
            /**
             * Translated
             * @description 번역문. 방향에 따라 현지어 또는 한국어.
             */
            translated: string;
            /**
             * Reading
             * @description ko2local 이면 번역한 현지어의 한국어 독음. local2ko 이면 빈 문자열.
             */
            reading: string;
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    scan_menu_api_v1_menu_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_scan_menu_api_v1_menu_scan_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_item_api_v1_menu_item_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    locate_items_api_v1_menu_locate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_locate_items_api_v1_menu_locate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_voice_api_v1_chat_voice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_chat_voice_api_v1_chat_voice_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
